# Generated by Django 3.1.4 on 2021-04-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='belongs_to',
            new_name='project',
        ),
    ]
