# Generated by Django 3.1.4 on 2021-01-03 07:55

from django.db import migrations
import server.backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210103_0531'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', server.backend.models.WaveUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='invited_at',
            new_name='invitation_accepted_at',
        ),
    ]
